huh:
    list:
        config_element_types:
            - { name: isotopeImage, class: HeimrichHannot\IsotopeBundle\ConfigElementType\IsotopeImageListConfigElementType }
        items:
            - { name: isotopeCollectionItem, class: HeimrichHannot\IsotopeBundle\ListItem\IsotopeCollectionItem }
        templates:
            item:
                - { name: isotopeListItem, template: "@HeimrichHannotContaoIsotope/item/list_item_isotope.html.twig" }