services:
  _defaults:
    public: true

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

  huh.isotope.listener.hooks.isotope:
    class: HeimrichHannot\IsotopeBundle\EventListener\IsotopeHookListener
    arguments: ['@huh.isotope.manager.productdata', '@huh.isotope.manager', '@huh.isotope.attribute.booking', '@huh.request']
  huh.isotope.listener.hooks:
    class: HeimrichHannot\IsotopeBundle\EventListener\HookListener
    arguments: ['@huh.isotope.manager.productdata']
  huh.isotope.listener.callback.product:
    class: HeimrichHannot\IsotopeBundle\EventListener\ProductCallbackListener
    arguments: ['@contao.framework', '@huh.request', '@huh.utils.container', '@huh.isotope.manager.productdata', '@huh.isotope.attribute.booking', '@twig']
  huh.isotope.listener.callback.productcollection:
    class: HeimrichHannot\IsotopeBundle\EventListener\ProductCollectionCallbackListener
    arguments: ['@contao.framework', '@huh.isotope.manager', '@huh.isotope.manager.productdata']