services:
  _defaults:
    autoconfigure: true
    public: true

  huh.isotope.helper.download:
    class: HeimrichHannot\IsotopeBundle\Helper\DownloadHelper
    arguments: ['@contao.framework', '@huh.request']
  huh.isotope.helper.product:
    class: HeimrichHannot\IsotopeBundle\Helper\ProductHelper
    arguments: ['@contao.framework']

# Manager

  huh.isotope.manager:
    class: HeimrichHannot\IsotopeBundle\Manager\IsotopeManager
    arguments:
      - '@huh.isotope.manager.productdata'
      - '@huh.isotope.attribute.stock'
      - '@huh.isotope.attribute.maxordersize'
      - '@huh.utils.container'
      - '@contao.framework'
  huh.isotope.manager.productdata:
    class: HeimrichHannot\IsotopeBundle\Manager\ProductDataManager
    arguments: ['@contao.framework']
  huh.isotope.ajax_manager:
    class: HeimrichHannot\IsotopeBundle\Manager\AjaxManager
  huh.isotope.manager.list:
    class: HeimrichHannot\IsotopeBundle\Manager\ProductListManager
    arguments:
      - '@contao.framework'

# Attributes

  huh.isotope.attribute.stock:
    class: HeimrichHannot\IsotopeBundle\Attribute\StockAttribute
  huh.isotope.attribute.maxordersize:
    class: HeimrichHannot\IsotopeBundle\Attribute\MaxOrderSizeAttribute
  huh.isotope.attribute.booking:
    class: HeimrichHannot\IsotopeBundle\Attribute\BookingAttributes
    arguments: ['@contao.framework', '@huh.isotope.manager.productdata', '@huh.utils.model', '@translator', '@huh.isotope.manager']

# Commands

  huh.isotope.command.upgrade:
    class: HeimrichHannot\IsotopeBundle\Command\UpgradeCommand
    arguments: ['@contao.framework', '@huh.isotope.manager.productdata']

# Controller
  HeimrichHannot\IsotopeBundle\Controller\BackendController:
    arguments: ['@contao.framework', '@huh.isotope.attribute.booking']