services:
  _defaults:
    autoconfigure: true

  huh.isotope.helper.download:
    class: HeimrichHannot\IsotopeBundle\Helper\DownloadHelper
    public: true
    arguments: ['@contao.framework', '@huh.request']
  huh.isotope.helper.product:
    class: HeimrichHannot\IsotopeBundle\Helper\ProductHelper
    public: true
    arguments: ['@contao.framework']

# Manager

  huh.isotope.manager:
    class: HeimrichHannot\IsotopeBundle\Manager\IsotopeManager
    public: true
    arguments:
      - '@huh.isotope.manager.productdata'
      - '@huh.isotope.attribute.stock'
      - '@huh.isotope.attribute.maxordersize'
      - '@huh.utils.container'
      - '@contao.framework'
  huh.isotope.manager.productdata:
    class: HeimrichHannot\IsotopeBundle\Manager\ProductDataManager
  huh.isotope.ajax_manager:
    class: HeimrichHannot\IsotopeBundle\Manager\AjaxManager
    public: true
  huh.isotope.product_collection_manager:
      class: HeimrichHannot\IsotopeBundle\Manager\ProductCollectionManager
      public: true

# Event Listener

  huh.isotope.listener.hooks.isotope:
    class: HeimrichHannot\IsotopeBundle\EventListener\IsotopeHookListener
    arguments: ['@huh.isotope.manager.productdata', '@huh.isotope.manager']
  huh.isotope.listener.hooks:
    class: HeimrichHannot\IsotopeBundle\EventListener\HookListener
    arguments: ['@huh.isotope.manager.productdata']
  huh.isotope.listener.callback.product:
    class: HeimrichHannot\IsotopeBundle\EventListener\ProductCallbackListener
    arguments: ['@contao.framework', '@huh.request', '@huh.utils.container', '@huh.isotope.manager.productdata']
  huh.isotope.listener.callback.productcollection:
    class: HeimrichHannot\IsotopeBundle\EventListener\ProductCollectionCallbackListener
    arguments: ['@contao.framework', '@huh.isotope.manager', '@huh.isotope.manager.productdata']

# Attributes

  huh.isotope.attribute.stock:
    class: HeimrichHannot\IsotopeBundle\Attribute\StockAttribute
  huh.isotope.attribute.maxordersize:
    class: HeimrichHannot\IsotopeBundle\Attribute\MaxOrderSizeAttribute
  huh.isotope.attribute.booking:
    class: HeimrichHannot\IsotopeBundle\Attribute\BookingAttributes
    arguments: ['@contao.framework', '@huh.isotope.manager.productdata', '@huh.utils.model', '@translator']

# Commands

  huh.isotope.command.upgrade:
    class: HeimrichHannot\IsotopeBundle\Command\UpgradeCommand
    arguments: ['@contao.framework', '@huh.isotope.manager.productdata']